/*
vp_bundle.c - the host half of a release bundle (see vp_bundle.h)
*/

#include "virtpass/vp_bundle.h"

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <direct.h> /* _mkdir() */
#include <io.h>     /* _setmode() */
#else
#include <unistd.h> /* unlink() / rmdir() / mkdir() */
#endif

#ifdef _WIN32
/* MAX_PATH is the CRTs' limit, not this buffer's: keeping the buffer bigger
 * costs nothing and avoids pulling <windows.h> in here for one constant. */
#define BUNDLE_PATH_MAX 2048
#define bundle_mkdir(p) _mkdir(p)
/* The guest's tree is the guest's; a host path that is a reparse point (a
 * junction, i.e. what "symlink" means on Windows) is removed by rmdir() the
 * way the shim does it, so unlink() first and rmdir() after, like the core. */
#define bundle_rmdir(p) rmdir(p)
#define bundle_unlink(p) unlink(p)
#else
#define BUNDLE_PATH_MAX 4096
#define bundle_mkdir(p) mkdir(p, 0755)
#define bundle_rmdir(p) rmdir(p)
#define bundle_unlink(p) unlink(p)
#endif

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

static bool bundle_join(char* out, size_t size, const char* directory, const char* name)
{
    int wrote = snprintf(out, size, "%s/%s", directory, name);
    return wrote >= 0 && (size_t)wrote < size;
}

/* Windows compares paths without case; Android does not. The prefix a guest
 * names is always spelled the same way, so this only matters for a typed-in
 * command line. */
static bool bundle_prefix_is(const char* text, const char* prefix)
{
#ifdef _WIN32
    return _strnicmp(text, prefix, strlen(prefix)) == 0;
#else
    return strncmp(text, prefix, strlen(prefix)) == 0;
#endif
}

// ---------------------------------------------------------------------------
// Files the archive does not ship
// ---------------------------------------------------------------------------

/* Write one host file into the materialized rootfs. It is a *host* file, and a
 * host file is what the guest sees: the shadow index only supplies what the host
 * cannot express (symlinks), so a name we write wins over the archive. */
static bool bundle_write_file(const char* dest, const char* guest_path, const char* contents)
{
    char path[BUNDLE_PATH_MAX];
    char* at;
    size_t len = strlen(contents);
    FILE* file;

    if (strlen(dest) + strlen(guest_path) + 1 > sizeof(path)) {
        return false;
    }
    snprintf(path, sizeof(path), "%s%s", dest, guest_path);
    for (at = path + strlen(dest); *at; ++at) {
        if (*at == '/' || *at == '\\') {
            char saved = *at;
            *at = 0;
            bundle_mkdir(path);
            *at = saved;
        }
    }

    file = fopen(path, "wb");
    if (!file) {
        return false;
    }
    bool ok = fwrite(contents, 1, len, file) == len;
    fclose(file);
    return ok;
}

/* inittab: Alpine's own starts /sbin/openrc, which the minirootfs does not ship,
 * so a session started from it never reaches a shell. Ours runs one on the run's
 * console - the session the host attached, which the core answers as both
 * /dev/console and /dev/tty1.
 *
 * /proc/mounts: the archive has /proc as an empty directory and /etc/mtab is a
 * symlink to ../proc/mounts. A generated listing is what mount(8) and anything
 * that reads mtab expect; the mount table will generate it properly once there
 * is one, and until then these are the mounts the guest is really given. */
static const char* bundle_inittab =
    "# Written by the VirtPass host at install time (handover.md, Step 2).\n"
    "#\n"
    "# The archive ships Alpine's inittab, whose sysinit is /sbin/openrc - a\n"
    "# package the minirootfs does not contain - so it never reaches a shell.\n"
    "# This one runs a shell on the run's own console instead: a userland guest\n"
    "# has exactly one terminal, which the core answers as /dev/console and as\n"
    "# every /dev/ttyN (so it works whatever tty an inittab names).\n"
    "tty1::respawn:/bin/sh\n";

static const char* bundle_mounts =
    "# Generated by the VirtPass host: the namespace the guest is given.\n"
    "/dev/root / auto rw,relatime 0 0\n"
    "proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0\n"
    "sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0\n"
    "devtmpfs /dev devtmpfs rw,nosuid,size=65536k,mode=755 0 0\n"
    "devpts /dev/pts devpts rw,nosuid,noexec,relatime,mode=620 0 0\n"
    "tmpfs /tmp tmpfs rw,nosuid,nodev,relatime 0 0\n";

static bool bundle_write_session_files(const char* dest)
{
    return bundle_write_file(dest, "/etc/inittab", bundle_inittab) &&
           bundle_write_file(dest, "/proc/mounts", bundle_mounts);
}

// ---------------------------------------------------------------------------
// Mounting a run
// ---------------------------------------------------------------------------

static vp_rootfs_t* g_mounted = NULL;

void vp_bundle_unmount(void)
{
    if (g_mounted) {
        vp_rootfs_close(g_mounted);
        g_mounted = NULL;
    }
}

bool vp_bundle_mount(rvvm_machine_t* machine, const char* rootfs_tar_gz, const char* dest,
                     vp_bundle_stats_t* stats, const char** error)
{
    const char* local_error = NULL;
    vp_rootfs_t* rootfs;
    char pts[BUNDLE_PATH_MAX];

    if (!error) {
        error = &local_error;
    }
    *error = NULL;
    if (stats) {
        stats->entries = 0;
        stats->files = 0;
    }
    if (!machine || !rootfs_tar_gz || !dest) {
        *error = "no bundle was named";
        return false;
    }

    /* A previous run's index dies with its machine. */
    vp_bundle_unmount();

    rootfs = vp_rootfs_open(rootfs_tar_gz, error);
    if (!rootfs) {
        return false;
    }
    size_t written = vp_rootfs_extract(rootfs, dest, error);
    if (!written) {
        vp_rootfs_close(rootfs);
        return false;
    }
    g_mounted = rootfs;
    if (stats) {
        stats->entries = vp_rootfs_count(rootfs);
        stats->files = written;
    }

    /* Not fatal: a guest with no inittab is still a guest, and it says so. */
    (void)bundle_write_session_files(dest);
    /* The devices themselves are synthesized by the core, but the directory they
     * live in is the host's: the archive ships /dev empty, with no pts under it,
     * and a guest that mounts devpts needs somewhere to mount it. */
    if (bundle_join(pts, sizeof(pts), dest, "dev/pts")) {
        bundle_mkdir(pts);
    }

    rvvm_user_set_prefix(machine, dest);
    rvvm_user_set_shadow(machine, vp_rootfs_shadow(rootfs));
    return true;
}

// ---------------------------------------------------------------------------
// Apps
// ---------------------------------------------------------------------------

static void bundle_remove_tree(const char* path)
{
    DIR* dir = opendir(path);
    struct dirent* de;

    if (dir) {
        while ((de = readdir(dir)) != NULL) {
            char child[BUNDLE_PATH_MAX];
            if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, "..")) {
                continue;
            }
            if (!bundle_join(child, sizeof(child), path, de->d_name)) {
                continue;
            }
            if (opendir(child)) {
                bundle_remove_tree(child);
            } else {
                bundle_unlink(child);
            }
        }
        closedir(dir);
    }
    bundle_rmdir(path);
}

static void bundle_mkdir_p(const char* path)
{
    char work[BUNDLE_PATH_MAX];
    char* at;

    snprintf(work, sizeof(work), "%s", path);
    for (at = work + 1; *at; ++at) {
        if (*at == '\\' || *at == '/') {
            char saved = *at;
            *at = 0;
            bundle_mkdir(work);
            *at = saved;
        }
    }
    bundle_mkdir(work);
}

bool vp_bundle_app_id_from_guest_path(const char* guest_path, char* out, size_t size)
{
    static const char prefix[] = "data/app/";
    const char* at = guest_path;
    const char* end;
    size_t len;

    if (!at) {
        return false;
    }
    while (*at == '/' || *at == '\\') {
        at++;
    }
    if (!bundle_prefix_is(at, prefix)) {
        return false;
    }
    at += sizeof(prefix) - 1;
    end = at;
    while (*end && *end != '/' && *end != '\\') {
        end++;
    }
    len = (size_t)(end - at);
    /* "/data/app" alone, or an id with no entry point after it, is not a launch
     * target: the entry is named by the manifest, and the host is not going to
     * guess it. */
    if (!len || *end == 0 || len + 1 > size) {
        return false;
    }
    memcpy(out, at, len);
    out[len] = 0;
    return strcmp(out, ".") != 0 && strcmp(out, "..") != 0;
}

bool vp_bundle_install_app(const char* apps_tar_gz, const char* dest, const char* app_id,
                           char* assets_root, size_t assets_root_size, const char** error)
{
    const char* local_error = NULL;
    char app_tree[BUNDLE_PATH_MAX];
    char app_dir[BUNDLE_PATH_MAX];
    char data_dir[BUNDLE_PATH_MAX];
    char assets[BUNDLE_PATH_MAX];
    vp_rootfs_t* apps;
    vp_app_t manifest;
    struct stat st;
    size_t written;

    if (!error) {
        error = &local_error;
    }
    *error = NULL;
    if (assets_root && assets_root_size) {
        assets_root[0] = 0;
    }
    if (!apps_tar_gz || !dest) {
        *error = "no bundle was named";
        return false;
    }

    /* Isolation first: whatever a previous run left there goes, so this run can
     * only ever see the app it was given - and a run with no app sees none. */
    if (bundle_join(app_tree, sizeof(app_tree), dest, "data/app")) {
        bundle_remove_tree(app_tree);
    }
    if (!app_id || !*app_id) {
        return true;
    }

    apps = vp_rootfs_open(apps_tar_gz, error);
    if (!apps) {
        return false;
    }
    if (!vp_rootfs_app_manifest(apps, app_id, &manifest)) {
        *error = "the archive declares no such app";
        vp_rootfs_close(apps);
        return false;
    }
    if (!bundle_join(app_dir, sizeof(app_dir), app_tree, app_id)) {
        *error = "the app id is too long for the host destination";
        vp_rootfs_close(apps);
        return false;
    }
    written = vp_rootfs_install_app(apps, app_id, app_dir, error);
    vp_rootfs_close(apps);
    if (!written) {
        return false;
    }

    /* The app's writable state, and the app's own resources: the caller points
     * the asset mount at the latter, which is what makes /assets per-app. */
    if (snprintf(data_dir, sizeof(data_dir), "%s/data/data/%s", dest, app_id) >=
        (int)sizeof(data_dir)) {
        *error = "the app id is too long for the host destination";
        return false;
    }
    bundle_mkdir_p(data_dir);

    if (assets_root && assets_root_size) {
        if (snprintf(assets, sizeof(assets), "%s/assets", app_dir) < 0 ||
            stat(assets, &st) != 0 || !S_ISDIR(st.st_mode)) {
            assets[0] = 0;
        } else {
            snprintf(assets_root, assets_root_size, "%s", assets);
        }
    }
    return true;
}

size_t vp_bundle_list_apps(const char* apps_tar_gz, vp_bundle_app_t* out, size_t max)
{
    const char* error = NULL;
    vp_rootfs_t* apps;
    /* Heap, not the stack: VP_BUNDLE_APPS_MAX entries is tens of kilobytes, and
     * this is a picker-time read, not a hot path. */
    vp_app_t* list = calloc(VP_BUNDLE_APPS_MAX, sizeof(*list));
    size_t found, n, i;

    if (!apps_tar_gz || !out || !max || !list) {
        free(list);
        return 0;
    }
    apps = vp_rootfs_open(apps_tar_gz, &error);
    if (!apps) {
        free(list);
        return 0; // no bundle is not an error: a host may run without one
    }
    found = vp_rootfs_apps(apps, list, VP_BUNDLE_APPS_MAX);
    n = (found < (size_t)VP_BUNDLE_APPS_MAX) ? found : (size_t)VP_BUNDLE_APPS_MAX;
    for (i = 0; i < n && i < max; i++) {
        snprintf(out[i].id, sizeof(out[i].id), "%s", list[i].id);
        snprintf(out[i].guest_path, sizeof(out[i].guest_path), "%s/%s/%s",
                 VP_GUEST_APP_DIR, list[i].id, list[i].entry);
        snprintf(out[i].args, sizeof(out[i].args), "%s", list[i].args);
    }
    vp_rootfs_close(apps);
    free(list);
    return n;
}

// ---------------------------------------------------------------------------
// The /assets mount
// ---------------------------------------------------------------------------

static char g_assets_root[BUNDLE_PATH_MAX] = ".";

void vp_bundle_set_assets_root(const char* dir)
{
    if (dir && *dir) {
        snprintf(g_assets_root, sizeof(g_assets_root), "%s", dir);
    }
}

/* Which tree a call is about. A host that can have several runs at once (the
 * Android host boots one guest per card) passes its run's own root as the mount
 * userdata, because a process-global root would let one run read another's
 * resources. A host with a single run at a time (the WinHost) leaves it NULL and
 * uses the root set above. */
static const char* asset_root_of(void* user)
{
    return (user && *(const char*)user) ? (const char*)user : g_assets_root;
}

/* Resolve an asset name under the root, refusing anything that climbs out of it:
 * the tree belongs to the guest and must not turn into a way to read the host's
 * disk. Returns false when @name is not a plain relative path. */
static bool asset_host_path(const char* root, char* out, size_t size, const char* name)
{
    if (!name || !*name || name[0] == '/' || name[0] == '\\' || strstr(name, "..")) {
        return false;
    }
    /* APK asset names use '/', and so does the app payload this serves, so a
     * nested name like "fonts/x.ttf" resolves as-is. */
    return bundle_join(out, size, root, name);
}

static int asset_open_fd(void* user, const char* name)
{
    char path[BUNDLE_PATH_MAX];
    int fd;

    if (!asset_host_path(asset_root_of(user), path, sizeof(path), name)) {
        return -EINVAL;
    }
    fd = open(path, O_RDONLY);
    if (fd < 0) {
        return -ENOENT;
    }
#ifdef _WIN32
    /* The guest reads raw bytes: no CRLF translation on the way through. */
    _setmode(fd, _O_BINARY);
#endif
    return fd;
}

static int64_t asset_size(void* user, const char* name)
{
    char path[BUNDLE_PATH_MAX];
    struct stat st;

    if (!asset_host_path(asset_root_of(user), path, sizeof(path), name)) {
        return -EINVAL;
    }
    if (stat(path, &st) != 0) {
        return -ENOENT;
    }
    /* A directory says so by refusing to answer a size - the core then asks
     * open_dir() and reports S_IFDIR. */
    if (S_ISDIR(st.st_mode)) {
        return -EISDIR;
    }
    return (int64_t)st.st_size;
}

static void* asset_open_dir(void* user, const char* name)
{
    char path[BUNDLE_PATH_MAX];
    const char* root = asset_root_of(user);

    if (!name || !*name) {
        /* The mount root is the asset directory itself. */
        snprintf(path, sizeof(path), "%s", root);
    } else if (!asset_host_path(root, path, sizeof(path), name)) {
        return NULL;
    }
    return opendir(path);
}

static const char* asset_dir_next(void* user, void* dir)
{
    struct dirent* de;

    (void)user;
    de = readdir(dir);
    return de ? de->d_name : NULL; /* "." and ".." are the core's to report */
}

static void asset_dir_close(void* user, void* dir)
{
    (void)user;
    closedir(dir);
}

static const rvvm_asset_ops_t bundle_asset_ops = {
    .open_fd = asset_open_fd,
    .size = asset_size,
    .open_dir = asset_open_dir,
    .dir_next = asset_dir_next,
    .dir_close = asset_dir_close,
};

const rvvm_asset_ops_t* vp_bundle_assets(void)
{
    return &bundle_asset_ops;
}
