#Requires -Version 5.1
<#
.SYNOPSIS
    Mount namespace end-to-end: mount(2), umount2(2) and /proc/mounts.

.DESCRIPTION
    A guest runs with no kernel behind it, so the namespace it sees is described
    by rvvm_user.c's mount table and nothing else. mount(2) used to answer
    success without changing anything, and /proc/mounts used to be a string
    constant in vp_bundle.c that listed a devpts mount nothing implemented. Both
    are now the same table. This driver starts one `ash --serve` core and
    asserts on the guest's own output:

      table       /proc/mounts is the default namespace: the root, /dev, /sys,
                  /proc, /tmp and /var/tmp, with the VirtPass header, and no
                  devpts - there is no devpts mount behind /dev.
      namespace   a mount made in one session is visible in the NEXT one, and
                  unmounting it is visible too. This is the property the table
                  got wrong first: it lived in the per-process context, and
                  busybox's mount is a child that mounts and exits, so the mount
                  died with it - mount(2) said 0, umount(2) said EINVAL, and
                  /proc/mounts never mentioned it.
      errors      EBUSY over an existing mount point, ENOSYS for a filesystem
                  this core does not provide, EINVAL for a flag nothing
                  enforces, EINVAL for umounting something that is not mounted.
      served      what a mount does NOT do yet. A mounted filesystem is recorded
                  and reported, but the mount point does not serve it: after
                  `mount -t proc proc /mnt`, /mnt/uptime does not exist. The
                  provider column distinguishes what /proc/mounts says from what
                  resolves, and only the first is wired up. This check pins that
                  so the day it changes, it changes on purpose.

    Every `-c` client is a separate session and therefore a separate process, so
    the namespace checks are also the cross-process ones.

.PARAMETER Port
    Port the core listens on (default 7931, off the guest default 7900).

.PARAMETER Exe
    The host binary. Defaults to the build tree's rvvm_ash.

.EXAMPLE
    pwsh ./tools/mount_e2e.ps1
#>
param(
    [int]$Port = 7931,
    [string]$Exe = (Join-Path $PSScriptRoot '..\release.windows.x86_64\rvvm_ash_x86_64.exe')
)

$ErrorActionPreference = 'Stop'
$exe = (Resolve-Path -LiteralPath $Exe).Path
$dir = Split-Path $exe
$fails = 0
. (Join-Path $PSScriptRoot 'ash_sock.ps1')

function TS() { "[" + ([Environment]::TickCount64).ToString().PadLeft(9) + " ms] " }
function Check($ok, $what) {
    if ($ok) { "$(TS)ok   $what" } else { "$(TS)FAIL $what"; $script:fails++ }
}

# One client run: attach to the core, ask for the command, return its output with
# the terminal escapes stripped.
function Client([string]$cmd) {
    $r = & $exe --port $Port -c $cmd 2>$null
    ($r -join "`n") -replace "`e\[[0-9;?]*[A-Za-z]", ''
}

# The guest's own exit status for a command. Asked for rather than taken from
# $LASTEXITCODE because the client's own status is the session's, not the
# command's - and every error case here is about the command's.
function ClientRc([string]$cmd) {
    $r = Client "$cmd`necho __rc=`$?"
    if ($r -match '__rc=(-?\d+)') { [int]$Matches[1] } else { -1 }
}

$out = Join-Path $env:TEMP 'mount_e2e_core_out.txt'
$err = Join-Path $env:TEMP 'mount_e2e_core_err.txt'
Remove-Item $out, $err -ErrorAction SilentlyContinue

# A stale core from an earlier run would answer for us: make sure ours is the one.
Get-Process -Name 'rvvm_ash_x86_64' -ErrorAction SilentlyContinue |
    Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 300

$core = Start-Process -FilePath $exe -ArgumentList '--serve', '--port', "$Port" `
                      -WorkingDirectory $dir -PassThru `
                      -RedirectStandardOutput $out -RedirectStandardError $err -NoNewWindow

$up = Wait-AshUp -Exe $exe -Port $Port -Process $core
Check $up "the core (ash --serve) publishes its endpoint (port $Port)"
if (-not $up) {
    try { $core.Kill() } catch { }
    "--- core output ---"; Get-Content $out -ErrorAction SilentlyContinue
    "--- core stderr ---"; Get-Content $err -ErrorAction SilentlyContinue
    exit 1
}

try {
# --- the default namespace --------------------------------------------------
$r = Client 'cat /proc/mounts'
Check ($r -match '# Generated by the VirtPass host') "/proc/mounts carries the VirtPass header"
Check ($r -match '(?m)^/dev/root / auto rw') "/proc/mounts has the root filesystem"
foreach ($m in @('/dev devtmpfs', '/sys sysfs', '/proc proc', '/tmp tmpfs', '/var/tmp tmpfs')) {
    Check ($r -match ('(?m)^\S+ ' + [regex]::Escape($m) + ' ')) "/proc/mounts lists $m"
}
# The lie this replaced: a devpts mount on /dev/pts that nothing implements.
Check ($r -notmatch 'devpts') "/proc/mounts claims no devpts mount"
# Six lines plus the header, and nothing else: this file is generated from the
# table now, so a mount it does not know about cannot appear here.
Check ((($r -split "`n" | Where-Object { $_ -match '\S' }).Count) -eq 7) `
      "/proc/mounts is exactly the six default mounts plus its header"

# --- the namespace is shared across sessions --------------------------------
# /mnt in one session, read back from the next: this is the check the per-context
# table failed, and it is the whole reason the table is a namespace.
$rc = ClientRc 'mount -t tmpfs none /mnt'
Check ($rc -eq 0) "mount -t tmpfs none /mnt succeeds (rc $rc)"

$r = Client 'cat /proc/mounts'
Check ($r -match '(?m)^\S+ /mnt tmpfs rw') "a NEW session sees the mount another session made"
Check ($r -match '(?m)^\S+ /mnt tmpfs rw') "/proc/mounts names it with the fstype it was mounted as"

# Mounting over it is EBUSY, which also proves the lookup found the existing one
# rather than adding a second entry for the same path.
$rc = ClientRc 'mount -t tmpfs none /mnt'
Check ($rc -ne 0) "mounting over an existing mount point fails (rc $rc)"

$rc = ClientRc 'umount /mnt'
Check ($rc -eq 0) "umount /mnt succeeds (rc $rc)"

$r = Client 'cat /proc/mounts'
Check ($r -notmatch '(?m)^\S+ /mnt ') "a NEW session sees the unmount"

# A second umount has nothing to remove, and says so.
$rc = ClientRc 'umount /mnt'
Check ($rc -ne 0) "umounting something that is not mounted fails (rc $rc)"

# --- the answers that are refusals -----------------------------------------
$rc = ClientRc 'mount -t tmpfs none /tmp'
Check ($rc -ne 0) "mounting over a default mount point fails (rc $rc, EBUSY)"
$r = Client 'mount -t tmpfs none /tmp'
Check ($r -match 'busy') "the EBUSY is reported as 'Resource busy'"

$rc = ClientRc 'mount -t reiserfs none /srv'
Check ($rc -ne 0) "mounting a filesystem this core does not provide fails (rc $rc, ENOSYS)"
$r = Client 'mount -t reiserfs none /srv'
Check ($r -match 'not implemented') "the ENOSYS is reported as 'Function not implemented'"

# A flag nothing here enforces must be refused: accepting it would be a flag
# that lies to a guest which then writes to a nodev mount.
$rc = ClientRc 'mount -o nodev -t tmpfs none /opt'
Check ($rc -ne 0) "mount with MS_NODEV is refused (rc $rc, EINVAL)"
$r = Client 'mount -o nodev -t tmpfs none /opt'
Check ($r -match 'nvalid') "the EINVAL is reported as 'Invalid argument'"

# The root is the run's own filesystem, and the answer names that rather than
# complaining about the fstype.
$rc = ClientRc 'mount -t tmpfs none /'
Check ($rc -ne 0) "mounting over / is refused (rc $rc, EINVAL)"

# --- what a mount does not do yet ------------------------------------------
# Recorded and reported, but the mount point does not serve it: the provider
# column in the table tells /proc/mounts what a mount IS, and nothing routes
# resolution there yet. Pinned so the change is deliberate.
$rc = ClientRc 'mount -t proc proc /mnt'
Check ($rc -eq 0) "mount -t proc proc /mnt is accepted (rc $rc)"
$r = Client 'cat /proc/mounts'
Check ($r -match '(?m)^proc /mnt proc rw') "the proc mount is reported with fstype proc"
$r = Client 'cat /mnt/uptime'
Check ($r -match 'No such file') "NOT YET: the mount point does not serve the filesystem"
$rc = ClientRc 'umount /mnt'
Check ($rc -eq 0) "the proc mount unmounts again (rc $rc)"

} finally {
    # Leave the namespace as we found it: a mount left behind is a mount the next
    # run of this script inherits, and the default-table check would fail on it.
    Client 'umount /mnt' | Out-Null
    Client 'umount /srv' | Out-Null
    Client 'umount /opt' | Out-Null
    # Cleanup, even when a check threw - a lingering core holds the rootfs lock.
    Get-Process -Name 'rvvm_ash_x86_64' -ErrorAction SilentlyContinue |
        Stop-Process -Force -ErrorAction SilentlyContinue
}

if ($fails) {
    "=== FAIL: $fails check(s) ==="
    "--- core output ---"; Get-Content $out -ErrorAction SilentlyContinue
    "--- core stderr ---"; Get-Content $err -ErrorAction SilentlyContinue
    exit 1
}
"=== PASS: mount ==="
exit 0